version: 2.1

# add orbs including the slimdevops/slim-ai-test-orb@0.0.16
orbs:
  docker: circleci/docker@1.5.0
  slim-ai-test-orb: slimdevops/slim-ai-test-orb@0.0.16

parameters:
  image-name:
    description: slimpsv/orb-demo:fresh
    type: string
    # Add your container image here
    default: slimpsv/orb-demo:fresh 
  image-connector:
    description: dockerhub.public
    type: string
    #Connector used by slim to get the image eg:dockerhub.public
    default: dockerhub.public 
  cimg-tag:
    description: Which tag to be used for cimg/base.
    type: string
    # Which tag to be used for default circleci base image (cimg):  cimg/base:current
    default: current 

executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: << pipeline.parameters.image-name >>
    docker: 
      - image: cimg/base:<< pipeline.parameters.cimg-tag >>
        auth:
          # Add to Environment Variables your DockerHub Username and Password
          # Or set up credential management in Docker Hub (recommended)
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  buildAndPushContainerImage: 
    executor: docker-publisher 
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t << pipeline.parameters.image-name >> .
            docker push << pipeline.parameters.image-name >>

  slimScanAndProfile:
    docker:
      - image: cimg/base:<< pipeline.parameters.cimg-tag >>
    steps:
      - checkout
      # Run "Xray" profile on image
      - slim-ai-test-orb/xray:
          imageName: << pipeline.parameters.image-name >>
          imageConnector: << pipeline.parameters.image-connector >>
          cimgTag: << pipeline.parameters.cimg-tag >>
      - store_artifacts:
          path: /tmp/artifact-xray
          destination: xray-json
      # Run Slim Vulnerability Report on image
      - slim-ai-test-orb/vscan:
          imageName: << pipeline.parameters.image-name >>
          imageConnector: << pipeline.parameters.image-connector >>
          cimgTag: << pipeline.parameters.cimg-tag >>
      - store_artifacts:
          path: /tmp/artifact-vscan
          destination: vscan-json
      # Generate Readme.html summary of information with links to image on Slim Platform
      - store_artifacts:
          path: /tmp/artifact-readme
          destination: readme.html

workflows:
  engine-execution:
    jobs:
      - buildAndPushContainerImage
      - slimScanAndProfile:
          requires:
            - buildAndPushContainerImage
